services:
  calibre-web-automated-book-downloader-dev:
    extends:
      file: ./docker-compose.yml
      service: calibre-web-automated-book-downloader
    build:
      context: .
      dockerfile: Dockerfile
      target: cwa-bd
    environment:
      DEBUG: "true"
      ADMIN_PASSWORD: admin123
    volumes:
      - /tmp/cwa-book-downloader:/tmp/cwa-book-downloader
      - /tmp/cwa-book-downloader-log:/var/log/cwa-book-downloader
